version: '3.8'

services:

    mariadb:
      build: 
        context: ./requirements/mariadb
        args:
          MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
          MYSQL_USER: $MYSQL_USER
          MYSQL_PASSWORD: $MYSQL_PASSWORD
      image: mariadb
      container_name: mariadb
      env_file: .env
      volumes:
        - database:/var/lib/mysql
      restart: always
      networks: 
      - my_network

    wordpress:
      build: 
       context: ./requirements/wordpress
       args:
           MYSQL_USER: $MYSQL_USER
           MYSQL_PASSWORD: $MYSQL_PASSWORD
           ADMIN_USER: $ADMIN_USER
           ADMIN_PASSWORD: $ADMIN_PASSWORD
      image: wordpress
      container_name: wordpress
      # ports:
      #   - 9000:9000
      restart: always
      depends_on:
      - mariadb
      volumes:
      - wordpress_d:/var/www/html/
      env_file: .env
      networks: 
      - my_network
    
    nginx:
      build:
        context: ./requirements/nginx
      image: nginx
      container_name: nginx
      ports:
      - 443:443
      volumes:
      - wordpress_d:/var/www/html/
      restart: always
      depends_on:
      - wordpress
      networks: 
      - my_network

volumes:
  database:
    driver_opts:
      type: none
      o: bind
      device: /home/aennaki/data/database
  wordpress_d:
    driver_opts:
      type: none
      o: bind
      device: /home/aennaki/data/wordpress

networks:
  my_network:
    driver: bridge

